ccflags-y += -I$(srctree)/drivers/camera/flash/flash_drv
ccflags-y += -I$(srctree)/drivers/camera/interface

obj-$(CONFIG_SPRD_CAMERA_FLASH_OCP8137) += flash_ic_ocp8137.o
flash_ic_ocp8137-objs := flash_ic_ocp8137_drv.o
