obj-$(CONFIG_SPRD_CAMERA_CORE) += core/
obj-$(CONFIG_SPRD_CAMERA_CPP) += cpp/
obj-$(CONFIG_SPRD_CAMERA_FD) += fd/
obj-$(CONFIG_SPRD_CAMERA_FLASH) += flash/
obj-$(CONFIG_SPRD_CAMERA_MMDVFS) += mmdvfs/
obj-$(CONFIG_SPRD_CAMERA_SENSOR) += sensor/
