ccflags-y += -I$(srctree)/drivers/camera/common
ccflags-y += -I$(srctree)/drivers/camera/interface

obj-$(CONFIG_SPRD_CAMERA_CPP) := sprd_cpp.o
sprd_cpp-objs := lite_r6p0/cpp_core.o lite_r6p0/cpp_ioctl.o lite_r6p0/dma_drv.o lite_r6p0/rot_drv.o lite_r6p0/scale_drv.o
