ccflags-y += -I$(srctree)/drivers/camera/core/isp2.6/adpt/sharkl5pro/inc
ccflags-y += -I$(srctree)/drivers/camera/core/isp2.6/inc
ccflags-y += -I$(srctree)/drivers/camera/common
ccflags-y += -I$(srctree)/drivers/camera/interface
ccflags-y += -I$(srctree)/drivers/staging/android/ion

obj-$(CONFIG_SPRD_CAMERA_FD) += sprd_fd.o
sprd_fd-objs := fd2.0/fd_core.o fd2.0/fd_drv.o
